#!/bin/bash
#
# minicon - Minimization of filesystems for containers
# https://github.com/grycap/minicon
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

n=0
while [ $# -gt 0 ]; do
    if [ "${1:0:1}" == "-" -a "${1:1:1}" != "-" -a "${1:1:1}" != "" ]; then
        for f in $(echo "${1:1}" | sed 's/\(.\)/-\1 /g' ); do
            ARR[$n]="$f"
            n=$(($n+1))
        done
    else
        ARR[$n]="$1"
        n=$(($n+1))
    fi
    shift
done

n=0
while [ $n -lt ${#ARR[@]} ]; do
    PARAM="${ARR[$n]}"
    case "$PARAM" in
        --help | -h)            usage && finalize;;
        --strace)               STRACE=true;;
        --tarfile|-t)           n=$(($n+1))
                                TARFILE="${ARR[$n]}";;
        --|*)                   [ "$PARAM" == "--" ] && n=$(($n+1))
                                DOCKERIMAGE="$PARAM"
                                n=$(($n+1))
                                while [ $n -lt ${#ARR[@]} ]; do
                                  PARAM="${ARR[$n]}"
                                  COMMANDS="$COMMANDS$PARAM "
                                  n=$(($n+1))
                                done;;
    esac
    n=$(($n+1))
done

if [ "$DOCKERIMAGE" == "" ]; then
  echo "you must state a docker image" >&2
  exit 1
fi

C_TARFILE=$0
while [ -e "$C_TARFILE" ]; do
  C_TARFILE=./${RANDOM}_$(date +%s).tar
done
touch "$C_TARFILE"
PARAMS="-t /tmp/minicon/$C_TARFILE"

DOCKERPARAMS=
if [ "$STRACE" == "true" ]; then
    DOCKERPARAMS="--privileged"
    PARAMS="${PARAMS} --plugin=strace:seconds=3:exclude=/dev:exclude=/sys:exclude=/proc"
fi

docker run --rm -it $DOCKERPARAMS -v $PWD:/tmp/minicon $DOCKERIMAGE /tmp/minicon/minicon -l -v --debug --plugin=scripts $PARAMS ${COMMANDS[@]}
if [ "$TARFILE" != "" ]; then
  mv "$C_TARFILE" "$TARFILE"
  echo "$TARFILE"
else
  echo "$C_TARFILE"
fi